export const runtime = "nodejs";

import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";
import { wrapOpenAI } from "langsmith/wrappers";
import { traceable } from "langsmith/traceable";
import { retrieveChunks, RetrievedChunk } from "@/app/lib/pinecone";

// LangSmith-wrapped client for chat completions
const client = wrapOpenAI(new OpenAI());

// Raw OpenAI client for embeddings (no LangSmith wrapping needed)
const embedClient = new OpenAI();

function buildSystemPrompt(retrievedChunks: RetrievedChunk[]): string {
  const kbContext = retrievedChunks
    .map((chunk) => `### ${chunk.heading}\n${chunk.content}`)
    .join("\n\n---\n\n");

  return `You are an internal helpdesk AI agent. Use the retrieved knowledge base sections below to answer employee and CSM questions accurately.

Decision rules:
- ANSWER directly when you find clear, relevant information in the retrieved KB sections with high confidence
- ROUTE to a team when: the query is urgent/emergency/outage, requires hands-on assessment, involves sensitive HR/legal/security action, or you cannot find a confident KB answer
- OUT_OF_SCOPE when: the query has nothing to do with company operations (e.g. general knowledge, personal questions, weather, sports)

Tool use rules:
- Call create_linear_ticket when a CSM or employee reports a bug, requests a feature, or asks to track an issue in engineering
- You can ANSWER and also call create_linear_ticket in the same response — they are not mutually exclusive

You MUST respond with ONLY a valid JSON object — no markdown, no prose outside the JSON. Exact shape required:

{
  "decision": {
    "action": "answer" | "route" | "out_of_scope",
    "confidence": <0.0–1.0>,
    "reasoning": "<one sentence>"
  },
  "answer": {
    "text": "<clear formatted answer, use line breaks for readability>",
    "citations": ["<KB section heading>", ...]
  } | null,
  "routing": {
    "team": "<team name>",
    "reason": "<why routing>",
    "contact": "<email from KB>"
  } | null,
  "kb_sections_searched": ["<section heading>", ...]
}

Set "answer" to null when routing or out_of_scope. Set "routing" to null when answering or out_of_scope.

---

RETRIEVED KNOWLEDGE BASE SECTIONS:

${kbContext}`;
}

const TOOLS: OpenAI.Chat.ChatCompletionTool[] = [
  {
    type: "function",
    function: {
      name: "create_linear_ticket",
      description:
        "Create a Linear ticket for a bug report or feature request. Use when a CSM or employee reports a bug, requests a new feature, or asks to track an engineering issue.",
      parameters: {
        type: "object",
        properties: {
          title: {
            type: "string",
            description: "Short, descriptive ticket title",
          },
          description: {
            type: "string",
            description:
              "Detailed description of the bug or feature request, including context from the user's query",
          },
          type: {
            type: "string",
            enum: ["bug", "feature", "improvement"],
            description: "Type of ticket",
          },
          priority: {
            type: "string",
            enum: ["urgent", "high", "medium", "low"],
            description: "Priority level based on the user's query",
          },
          team: {
            type: "string",
            description:
              "Engineering team to assign to (e.g. Platform, Product, Infrastructure)",
          },
        },
        required: ["title", "description", "type", "priority", "team"],
      },
    },
  },
];

function mockCreateLinearTicket(args: {
  title: string;
  description: string;
  type: string;
  priority: string;
  team: string;
}) {
  const id = `ENG-${Math.floor(1000 + Math.random() * 9000)}`;
  return {
    id,
    title: args.title,
    description: args.description,
    type: args.type,
    priority: args.priority,
    team: args.team,
    status: "Todo",
    assignee: null,
    url: `https://linear.app/company/issue/${id}`,
    created_at: new Date().toISOString(),
  };
}

const JUDGE_SYSTEM_PROMPT = `You are an independent AI quality evaluator for an internal helpdesk system. You will receive a user query, the knowledge base sections that were retrieved as context, and the answer that was generated by a separate model.

Your job is to evaluate the quality of that answer. You have no knowledge of how the answer was produced — evaluate it purely on its merit against the query and the provided KB sections.

You MUST respond with ONLY a valid JSON object — no markdown, no prose outside the JSON:

{
  "score": <0.0–1.0>,
  "passed": <true if score >= 0.75>,
  "criteria": {
    "relevance": <0.0–1.0>,
    "completeness": <0.0–1.0>,
    "accuracy": <0.0–1.0>,
    "citation_quality": <0.0–1.0>
  },
  "feedback": "<one-sentence honest quality assessment>"
}

Scoring guide:
- relevance: Does the answer address what the user actually asked?
- completeness: Are all key aspects of the question covered?
- accuracy: Is the information factually correct based on the provided KB sections only?
- citation_quality: Are the correct KB sections cited to support the answer?

Be honest and critical. A score of 0.75 or above means the answer is production-ready.`;

async function runJudge(
  query: string,
  retrievedChunks: RetrievedChunk[],
  answerText: string | null
): Promise<unknown> {
  if (!answerText) {
    return {
      score: null,
      passed: null,
      criteria: null,
      feedback: "Query was routed or out of scope — no answer to evaluate.",
    };
  }

  const kbContext = retrievedChunks
    .map((c) => `### ${c.heading}\n${c.content}`)
    .join("\n\n---\n\n");

  const judgeResponse = await client.chat.completions.create({
    model: "gpt-5-mini",
    response_format: { type: "json_object" },
    messages: [
      { role: "system", content: JUDGE_SYSTEM_PROMPT },
      {
        role: "user",
        content: `Query: ${query}\n\nRetrieved KB sections:\n${kbContext}\n\nGenerated answer:\n${answerText}`,
      },
    ],
  });

  return JSON.parse(judgeResponse.choices[0].message.content ?? "{}");
}

type AgentResult = {
  decision: unknown;
  answer: unknown;
  routing: unknown;
  tool_results: unknown[];
  judge: unknown;
};

const runAgent = traceable(
  async (query: string): Promise<AgentResult> => {
    // RAG retrieval — embed the query and fetch top-4 chunks from Pinecone
    const retrieved = await retrieveChunks(embedClient, query, 4);

    const systemPrompt = buildSystemPrompt(retrieved);

    const messages: OpenAI.Chat.ChatCompletionMessageParam[] = [
      { role: "system", content: systemPrompt },
      { role: "user", content: query },
    ];

    // Build the rag_retrieval tool result (always present)
    const ragResult = {
      tool: "rag_retrieval",
      query,
      chunks: retrieved.map((c) => ({
        heading: c.heading,
        score: c.score,
        snippet: c.snippet,
      })),
    };

    // First call — agent decides whether to call a tool
    const first = await client.chat.completions.create({
      model: "gpt-5-mini",
      tools: TOOLS,
      tool_choice: "auto",
      messages,
    });

    const firstMessage = first.choices[0].message;
    messages.push(firstMessage);

    let linearTicket: ReturnType<typeof mockCreateLinearTicket> | null = null;

    // Execute tool calls if the agent requested them
    if (firstMessage.tool_calls?.length) {
      for (const call of firstMessage.tool_calls) {
        const tc = call as OpenAI.Chat.ChatCompletionMessageFunctionToolCall;
        if (tc.function.name === "create_linear_ticket") {
          const args = JSON.parse(tc.function.arguments);
          linearTicket = mockCreateLinearTicket(args);

          messages.push({
            role: "tool",
            tool_call_id: tc.id,
            content: JSON.stringify(linearTicket),
          });
        }
      }

      // Second call — agent produces final JSON response with tool results in context
      const second = await client.chat.completions.create({
        model: "gpt-5-mini",
        response_format: { type: "json_object" },
        messages,
      });

      const parsed: Record<string, unknown> = JSON.parse(
        second.choices[0].message.content ?? "{}"
      );

      const answerText = (parsed.answer as { text?: string } | null)?.text ?? null;
      const judge = await runJudge(query, retrieved, answerText);

      return {
        decision: parsed.decision,
        answer: parsed.answer ?? undefined,
        routing: parsed.routing ?? undefined,
        tool_results: [
          ragResult,
          ...(linearTicket ? [{ tool: "create_linear_ticket", ticket: linearTicket }] : []),
        ],
        judge,
      };
    }

    // No tool calls — parse the direct JSON response
    const parsed: Record<string, unknown> = JSON.parse(
      firstMessage.content ?? "{}"
    );

    const answerText = (parsed.answer as { text?: string } | null)?.text ?? null;
    const judge = await runJudge(query, retrieved, answerText);

    return {
      decision: parsed.decision,
      answer: parsed.answer ?? undefined,
      routing: parsed.routing ?? undefined,
      tool_results: [ragResult],
      judge,
    };
  },
  { name: "helpdesk-agent", run_type: "chain" }
);

export async function POST(req: NextRequest) {
  const body = await req.json();
  const query: string = body.query ?? "";

  if (!query.trim()) {
    return NextResponse.json({ error: "Query is required" }, { status: 400 });
  }

  try {
    const result = await runAgent(query);
    return NextResponse.json(result);
  } catch (err) {
    console.error("Helpdesk API error:", err);
    return NextResponse.json(
      { error: "Agent request failed. Check your OPENAI_API_KEY and PINECONE_API_KEY." },
      { status: 500 }
    );
  }
}
